language: go
sudo: false
go:
  - 1.x

before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls

script:
  - ./go.test.sh

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken $COVERALLS_TOKEN
  - bash <(curl -s https://codecov.io/bash)